#!/usr/bin/env python3
"""Export the selected nbshell theme for external applications.

Generates palette.sh plus dynamic configs for Kitty, btop, pi, lazygit, yazi,
and herdr (via theme-hook.sh). Run after every theme switch.
"""
from __future__ import annotations

import json
import os
import subprocess
import tempfile
import tomllib
from pathlib import Path

home = Path.home()
config_home = Path(os.environ.get("XDG_CONFIG_HOME", home / ".config"))
config_dir = config_home / "nbshell"
config = json.loads((config_dir / "config.json").read_text())
theme = str(config.get("theme") or "tokyo-night")
colors_path = config_dir / "themes" / theme / "colors.toml"
with colors_path.open("rb") as handle:
    c = tomllib.load(handle)


def get(key: str, fallback: str) -> str:
    return str(c.get(key, fallback))


def atomic_write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, temporary = tempfile.mkstemp(prefix=".nbshell.", dir=path.parent, text=True)
    try:
        with os.fdopen(fd, "w") as handle:
            handle.write(content)
        os.replace(temporary, path)
    finally:
        if os.path.exists(temporary):
            os.unlink(temporary)


bg = get("background", "#000000")
bg_dark = get("dark_background", bg)
bg_darker = get("darker_background", bg_dark)
bg_light = get("lighter_background", bg)
fg = get("foreground", "#ffffff")
fg_dim = get("dark_foreground", "#808080")
fg_bright = get("bright_foreground", fg)
muted = get("muted", "#808080")
mode = get("mode", "dark")
accent = get("accent", get("blue", "#5f87ff"))
selection = get("selection", bg_light)
red = get("red", "#ff0000")
green = get("green", "#00ff00")
yellow = get("yellow", "#ffff00")
blue = get("blue", accent)
magenta = get("magenta", "#ff00ff")
cyan = get("cyan", "#00ffff")
brown = get("brown", "#808000")

ansi = [
    bg, red, green, yellow, blue, magenta, cyan, fg,
    fg_dim,
    get("bright_red", red), get("bright_green", green), get("bright_yellow", yellow),
    get("bright_blue", blue), get("bright_magenta", magenta), get("bright_cyan", cyan),
    get("bright_foreground", fg),
]
names = [
    "BLACK", "RED", "GREEN", "YELLOW", "BLUE", "MAGENTA", "CYAN", "WHITE",
    "BRIGHT_BLACK", "BRIGHT_RED", "BRIGHT_GREEN", "BRIGHT_YELLOW",
    "BRIGHT_BLUE", "BRIGHT_MAGENTA", "BRIGHT_CYAN", "BRIGHT_WHITE",
]
values = {
    "THEME": theme,
    "MODE": mode,
    "BG": bg,
    "BG_DARK": bg_dark,
    "BG_LIGHT": bg_light,
    "FG": fg,
    "FG_DIM": fg_dim,
    "FG_BRIGHT": fg_bright,
    "ACCENT": accent,
    "ACCENT_ROLE": str(config.get("accent") or "theme"),
    "MUTED": muted,
    "SELECTION": selection,
}
values.update(dict(zip(names, ansi)))

_lines = [
    f"# Generated by nbshell-theme-sync — Theme: {theme}",
    "# Do not edit manually.",
    "",
]
_lines.extend(f"NB_{key}='{value}'" for key, value in values.items())
_lines.extend(["", f'NB_ANSI="{" ".join(ansi)}"', ""])
atomic_write(config_dir / "palette.sh", "\n".join(_lines))

# ── Kitty ────────────────────────────────────────────────────────────────
kitty_theme = f"""# Generated by nbshell-theme-sync — Theme: {theme}
foreground {fg}
background {bg}
selection_foreground {fg_bright}
selection_background {selection}
cursor {accent}
cursor_text_color {bg}
url_color {blue}
active_border_color {accent}
inactive_border_color {muted}
bell_border_color {yellow}
active_tab_foreground {fg_bright}
active_tab_background {selection}
inactive_tab_foreground {fg_dim}
inactive_tab_background {bg_dark}
color0 {ansi[0]}
color1 {ansi[1]}
color2 {ansi[2]}
color3 {ansi[3]}
color4 {ansi[4]}
color5 {ansi[5]}
color6 {ansi[6]}
color7 {ansi[7]}
color8 {ansi[8]}
color9 {ansi[9]}
color10 {ansi[10]}
color11 {ansi[11]}
color12 {ansi[12]}
color13 {ansi[13]}
color14 {ansi[14]}
color15 {ansi[15]}
"""
kitty_theme_path = config_dir / "kitty.conf"
atomic_write(kitty_theme_path, kitty_theme)
# Reload every running Kitty OS process. New installs use Kitty's cross-platform
# temporary directory; keep old cache/runtime locations for existing windows.
kitty_socket_dirs = [Path(os.environ.get("TMPDIR", "/tmp")), Path.home() / ".cache"]
xdg_runtime = os.environ.get("XDG_RUNTIME_DIR")
if xdg_runtime:
    kitty_socket_dirs.append(Path(xdg_runtime))
elif sys.platform.startswith("linux"):
    kitty_socket_dirs.append(Path(f"/run/user/{os.getuid()}"))
if subprocess.run(
    ["sh", "-c", "command -v kitty >/dev/null"], check=False
).returncode == 0:
    seen_kitty_sockets: set[Path] = set()
    for kitty_socket_dir in kitty_socket_dirs:
        for kitty_socket in kitty_socket_dir.glob("kitty-*"):
            if kitty_socket in seen_kitty_sockets or not kitty_socket.is_socket():
                continue
            seen_kitty_sockets.add(kitty_socket)
            subprocess.run(
                ["kitty", "@", "--to", f"unix:{kitty_socket}", "load-config"],
                check=False,
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
            )
# ── pi ───────────────────────────────────────────────────────────────────
pi_colors = {
    # Core UI
    "accent": accent,
    "border": bg_light,
    "borderAccent": accent,
    "borderMuted": muted,
    "success": green,
    "error": red,
    "warning": yellow,
    "muted": muted,
    "dim": fg_dim,
    "text": fg,
    "thinkingText": muted,
    # Backgrounds & content
    "selectedBg": bg_light,
    "scrollbarThumb": bg_light,
    "searchMatchBg": bg_light,
    "searchMatchText": fg,
    "userMessageBg": bg_light,
    "userMessageText": fg,
    "customMessageBg": bg_light,
    "customMessageText": fg,
    "customMessageLabel": accent,
    "toolPendingBg": bg_dark,
    "toolSuccessBg": bg_dark,
    "toolErrorBg": bg_dark,
    "toolTitle": accent,
    "toolOutput": fg,
    # Markdown
    "mdHeading": accent,
    "mdLink": blue,
    "mdLinkUrl": muted,
    "mdCode": cyan,
    "mdCodeBlock": fg,
    "mdCodeBlockBorder": muted,
    "mdQuote": muted,
    "mdQuoteBorder": muted,
    "mdHr": muted,
    "mdListBullet": cyan,
    # Diffs
    "toolDiffAdded": green,
    "toolDiffRemoved": red,
    "toolDiffContext": muted,
    # Syntax
    "syntaxComment": muted,
    "syntaxKeyword": magenta,
    "syntaxFunction": blue,
    "syntaxVariable": yellow,
    "syntaxString": green,
    "syntaxNumber": magenta,
    "syntaxType": cyan,
    "syntaxOperator": accent,
    "syntaxPunctuation": muted,
    # Thinking borders
    "thinkingOff": muted,
    "thinkingMinimal": accent,
    "thinkingLow": blue,
    "thinkingMedium": cyan,
    "thinkingHigh": magenta,
    "thinkingXhigh": red,
    "thinkingMax": red,
    "bashMode": yellow,
}
pi_theme = {
    "$schema": "https://raw.githubusercontent.com/earendil-works/pi/main/packages/coding-agent/src/modes/interactive/theme/theme-schema.json",
    "name": "nbshell",
    "colors": pi_colors,
}
atomic_write(
    Path(os.environ.get("PI_AGENT_DIR", home / ".pi/agent")) / "themes" / "nbshell.json",
    json.dumps(pi_theme, indent=2) + "\n",
)

# ── lazygit ──────────────────────────────────────────────────────────────
# lazygit 0.64+ 没有 customTheme 字段，主题必须内联在 config.yml 的 gui.theme 里。
lg_theme = f"""# 由 nbshell theme-sync.py 管理; 其它 lazygit 设置请放在 gui.theme 之外。
gui:
  theme:
    # BEGIN nbshell managed theme
    activeBorderColor:
      - "{accent}"
      - bold
    inactiveBorderColor:
      - "{muted}"
    searchingActiveBorderColor:
      - "{cyan}"
      - bold
    optionsTextColor:
      - "{blue}"
    selectedLineBgColor:
      - "{selection}"
    inactiveViewSelectedLineBgColor:
      - "{bg_light}"
    cherryPickedCommitFgColor:
      - "{blue}"
    cherryPickedCommitBgColor:
      - "{cyan}"
    markedBaseCommitFgColor:
      - "{blue}"
    markedBaseCommitBgColor:
      - "{yellow}"
    unstagedChangesColor:
      - "{red}"
    defaultFgColor:
      - "{fg}"
    # END nbshell managed theme
"""
atomic_write(config_home / "lazygit" / "config.yml", lg_theme)
config_home.joinpath("lazygit", "theme.yml").unlink(missing_ok=True)

# ── yazi ─────────────────────────────────────────────────────────────────
surface = bg_light
overlay = bg_dark
yazi_flavor = f"""# Generated by nbshell-theme-sync — Theme: {theme}
[app]
overall = {{ bg = "{bg}" }}

[mgr]
cwd = {{ fg = "{cyan}" }}
find_keyword = {{ fg = "{yellow}", bold = true, italic = true, underline = true }}
find_position = {{ fg = "{magenta}", bg = "reset", bold = true, italic = true }}
marker_copied = {{ fg = "{green}", bg = "{green}" }}
marker_cut = {{ fg = "{red}", bg = "{red}" }}
marker_marked = {{ fg = "{blue}", bg = "{blue}" }}
marker_selected = {{ fg = "{yellow}", bg = "{yellow}" }}
count_copied = {{ fg = "{bg}", bg = "{green}" }}
count_cut = {{ fg = "{bg}", bg = "{red}" }}
count_selected = {{ fg = "{bg}", bg = "{yellow}" }}
border_symbol = "│"
border_style = {{ fg = "{muted}" }}

[tabs]
active = {{ fg = "{bg}", bg = "{accent}", bold = true }}
inactive = {{ fg = "{accent}", bg = "{surface}" }}

[mode]
normal_main = {{ fg = "{bg}", bg = "{accent}", bold = true }}
normal_alt = {{ fg = "{accent}", bg = "{surface}" }}
select_main = {{ fg = "{bg}", bg = "{blue}", bold = true }}
select_alt = {{ fg = "{blue}", bg = "{surface}" }}
unset_main = {{ fg = "{bg}", bg = "{yellow}", bold = true }}
unset_alt = {{ fg = "{yellow}", bg = "{surface}" }}

[status]
perm_sep = {{ fg = "{muted}" }}
perm_type = {{ fg = "{accent}" }}
perm_read = {{ fg = "{yellow}" }}
perm_write = {{ fg = "{red}" }}
perm_exec = {{ fg = "{green}" }}
progress_label = {{ fg = "{fg}", bold = true }}
progress_normal = {{ fg = "{green}", bg = "{overlay}" }}
progress_error = {{ fg = "{yellow}", bg = "{red}" }}

[pick]
border = {{ fg = "{accent}" }}
active = {{ fg = "{magenta}", bold = true }}
inactive = {{ fg = "{muted}" }}

[input]
border = {{ fg = "{accent}" }}
title = {{ fg = "{accent}", bold = true }}
value = {{ fg = "{fg}" }}
selected = {{ fg = "{bg}", bg = "{accent}" }}

[cmp]
border = {{ fg = "{accent}" }}
active = {{ fg = "{blue}", bold = true }}
inactive = {{ fg = "{muted}" }}

[tasks]
border = {{ fg = "{accent}" }}
title = {{ fg = "{accent}", bold = true }}
hovered = {{ fg = "{green}", bold = true }}

[which]
cols = {{ fg = "{bg}", bg = "{green}" }}
mask = {{ fg = "{bg}", bg = "{blue}" }}
cand = {{ fg = "{green}", bg = "{bg_dark}" }}
rest = {{ fg = "{bg}", bg = "{green}" }}
desc = {{ fg = "{green}", bg = "{bg_dark}" }}
separator = "  "

[help]
on = {{ fg = "{green}" }}
run = {{ fg = "{accent}" }}
hovered = {{ fg = "{bg}", bg = "{accent}" }}
footer = {{ fg = "{bg}", bg = "{green}" }}

[spot]
border = {{ fg = "{accent}" }}
selected = {{ fg = "{bg}", bg = "{accent}" }}
text = {{ fg = "{fg}" }}

[notify]
title = {{ fg = "{yellow}", bold = true }}
content = {{ fg = "{fg}" }}

[filetype]
rules = []
"""
flavors_dir = config_home / "yazi" / "flavors" / f"{theme}.yazi"
atomic_write(flavors_dir / "flavor.toml", yazi_flavor)
yazi_theme = f"""# Generated by nbshell-theme-sync — Theme: {theme}
[flavor]
dark = "{theme}"
light = "{theme}"
"""
atomic_write(config_home / "yazi" / "theme.toml", yazi_theme)

# ── herdr (side effects) ─────────────────────────────────────────────────
hook = config_dir / "theme-hook.sh"
if os.access(hook, os.X_OK):
    subprocess.run([str(hook), theme, mode], check=False)
