#!/usr/bin/env bash
# Runs after nbshell exports ~/.config/nbshell/palette.sh.
# Synchronizes applications whose palettes are not managed directly by QML.
set -u

palette="${XDG_CONFIG_HOME:-$HOME/.config}/nbshell/palette.sh"
[ -r "$palette" ] || exit 0
# shellcheck disable=SC1090
. "$palette"

# Herdr supports a fixed set of named base themes. Pick the nearest built-in
# family, then override its UI tokens with the exact nbshell palette.
case "${NB_THEME:-}" in
  catppuccin-latte) herdr_base="catppuccin-latte" ;;
  catppuccin*) herdr_base="catppuccin" ;;
  tokyo-night) herdr_base="tokyo-night" ;;
  gruvbox) herdr_base="gruvbox" ;;
  kanagawa) herdr_base="kanagawa" ;;
  rose-pine) herdr_base="rose-pine" ;;
  nord) herdr_base="nord" ;;
  *solarized*|osaka-jade) herdr_base="solarized" ;;
  *) [ "${NB_MODE:-dark}" = light ] && herdr_base="catppuccin-latte" || herdr_base="terminal" ;;
esac

herdr_config="${XDG_CONFIG_HOME:-$HOME/.config}/herdr/config.toml"
if [ -f "$herdr_config" ]; then
  python3 - "$herdr_config" "$herdr_base" <<'PY'
from pathlib import Path
import re
import sys

path = Path(sys.argv[1])
base = sys.argv[2]
text = path.read_text()
colors = {}
for line in Path.home().joinpath('.config/nbshell/palette.sh').read_text().splitlines():
    m = re.match(r"NB_([A-Z_]+)='([^']*)'$", line)
    if m:
        colors[m.group(1)] = m.group(2)

block = f'''# BEGIN nbshell managed theme
[theme]
name = "{base}"
auto_switch = false

[theme.custom]
sidebar_bg = "{colors.get('BG_DARK', colors['BG'])}"
active_row_bg = "{colors.get('BG_LIGHT', colors['BG'])}"
selection_bg = "{colors.get('SELECTION', colors.get('BG_LIGHT', colors['BG']))}"
panel_bg = "{colors['BG']}"
accent = "{colors['ACCENT']}"
red = "{colors['RED']}"
green = "{colors['GREEN']}"
# END nbshell managed theme'''

managed = re.compile(r'# BEGIN nbshell managed theme.*?# END nbshell managed theme', re.S)
if managed.search(text):
    text = managed.sub(block, text)
else:
    # Replace the existing top-level [theme] section, including theme.custom if
    # present, while preserving all unrelated Herdr configuration.
    section = re.compile(r'(?ms)^\[theme\]\n.*?(?=^\[(?!theme(?:\.|\]))|\Z)')
    if section.search(text):
        text = section.sub(block + '\n\n', text, count=1)
    else:
        text = block + '\n\n' + text
path.write_text(text)
PY
  command -v herdr >/dev/null 2>&1 && herdr server reload-config >/dev/null 2>&1 || true
fi

# Kitty must be generated here as well as in theme-sync.py: appearance changes
# initiated inside nbshell call this hook directly after exporting palette.sh.
kitty_theme="${XDG_CONFIG_HOME:-$HOME/.config}/nbshell/kitty.conf"
python3 - "$kitty_theme" <<'PY'
from pathlib import Path
import os
import re
import sys
import tempfile

colors = {}
palette = Path.home() / ".config/nbshell/palette.sh"
for line in palette.read_text().splitlines():
    match = re.match(r"NB_([A-Z_]+)='([^']*)'$", line)
    if match:
        colors[match.group(1)] = match.group(2)

def color(name, fallback):
    return colors.get(name, fallback)

theme = color("THEME", "nbshell")
fg = color("FG", "#ffffff")
fg_bright = color("FG_BRIGHT", fg)
fg_dim = color("FG_DIM", "#808080")
bg = color("BG", "#000000")
bg_dark = color("BG_DARK", bg)
muted = color("MUTED", fg_dim)
accent = color("ACCENT", color("BLUE", "#5f87ff"))
selection = color("SELECTION", color("BG_LIGHT", bg))
ansi_names = [
    "BLACK", "RED", "GREEN", "YELLOW", "BLUE", "MAGENTA", "CYAN", "WHITE",
    "BRIGHT_BLACK", "BRIGHT_RED", "BRIGHT_GREEN", "BRIGHT_YELLOW",
    "BRIGHT_BLUE", "BRIGHT_MAGENTA", "BRIGHT_CYAN", "BRIGHT_WHITE",
]
ansi = [color(name, fg if index in (7, 15) else bg) for index, name in enumerate(ansi_names)]
lines = [
    f"# Generated by nbshell theme-hook — Theme: {theme}",
    f"foreground {fg}",
    f"background {bg}",
    f"selection_foreground {fg_bright}",
    f"selection_background {selection}",
    f"cursor {accent}",
    f"cursor_text_color {bg}",
    f"url_color {color('BLUE', accent)}",
    f"active_border_color {accent}",
    f"inactive_border_color {muted}",
    f"bell_border_color {color('YELLOW', accent)}",
    f"active_tab_foreground {fg_bright}",
    f"active_tab_background {selection}",
    f"inactive_tab_foreground {fg_dim}",
    f"inactive_tab_background {bg_dark}",
] + [f"color{index} {value}" for index, value in enumerate(ansi)]
path = Path(sys.argv[1])
path.parent.mkdir(parents=True, exist_ok=True)
fd, temporary = tempfile.mkstemp(prefix=".nbshell.", dir=path.parent, text=True)
try:
    with os.fdopen(fd, "w") as handle:
        handle.write("\n".join(lines) + "\n")
    os.replace(temporary, path)
finally:
    if os.path.exists(temporary):
        os.unlink(temporary)
PY

if command -v kitty >/dev/null 2>&1; then
  # Kitty uses the platform temporary directory; keep legacy locations too.
  kitty_socket_dirs=("${TMPDIR:-/tmp}" "${XDG_CACHE_HOME:-$HOME/.cache}")
  if [ -n "${XDG_RUNTIME_DIR:-}" ]; then
    kitty_socket_dirs+=("$XDG_RUNTIME_DIR")
  elif [ "$(uname -s)" = Linux ]; then
    kitty_socket_dirs+=("/run/user/$(id -u)")
  fi
  for kitty_socket_dir in "${kitty_socket_dirs[@]}"; do
    for kitty_socket in "$kitty_socket_dir"/kitty-*; do
      [ -S "$kitty_socket" ] || continue
      kitty @ --to "unix:$kitty_socket" load-config >/dev/null 2>&1 || true
    done
  done
fi

# btop reads custom themes from ~/.config/btop/themes on Linux and macOS.
# Its managed config already selects `color_theme = "current"`.
btop_theme="${XDG_CONFIG_HOME:-$HOME/.config}/btop/themes/current.theme"
python3 - "$btop_theme" <<'PY'
from pathlib import Path
import os
import re
import sys
import tempfile

colors = {}
palette = Path(os.environ.get("XDG_CONFIG_HOME", Path.home() / ".config")) / "nbshell/palette.sh"
for line in palette.read_text().splitlines():
    match = re.match(r"NB_([A-Z_]+)='([^']*)'$", line)
    if match:
        colors[match.group(1)] = match.group(2)

def color(name, fallback):
    return colors.get(name, fallback)

theme = color("THEME", "nbshell")
bg = color("BG", "#000000")
bg_dark = color("BG_DARK", bg)
bg_light = color("BG_LIGHT", bg)
fg = color("FG", "#ffffff")
fg_dim = color("FG_DIM", color("MUTED", "#808080"))
fg_bright = color("FG_BRIGHT", fg)
accent = color("ACCENT", color("BLUE", "#5f87ff"))
selection = color("SELECTION", bg_light)
red = color("RED", "#ff0000")
green = color("GREEN", "#00ff00")
yellow = color("YELLOW", "#ffff00")
blue = color("BLUE", accent)
magenta = color("MAGENTA", "#ff00ff")
cyan = color("CYAN", "#00ffff")

entries = {
    "main_bg": bg, "main_fg": fg, "title": fg_bright, "hi_fg": accent,
    "selected_bg": selection, "selected_fg": fg_bright,
    "inactive_fg": fg_dim, "graph_text": fg, "proc_misc": cyan,
    "cpu_box": accent, "mem_box": green, "net_box": blue,
    "proc_box": magenta, "div_line": color("MUTED", fg_dim),
    "temp_start": green, "temp_mid": yellow, "temp_end": red,
    "cpu_start": green, "cpu_mid": yellow, "cpu_end": red,
    "free_start": red, "free_mid": yellow, "free_end": green,
    "cached_start": cyan, "cached_mid": blue, "cached_end": magenta,
    "available_start": green, "available_mid": cyan, "available_end": blue,
    "used_start": green, "used_mid": yellow, "used_end": red,
    "download_start": green, "download_mid": cyan, "download_end": blue,
    "upload_start": blue, "upload_mid": magenta, "upload_end": red,
}
content = f"# Generated by nbshell theme-hook — Theme: {theme}\n"
content += "# Do not edit manually. Restart btop to apply a changed theme.\n\n"
content += "\n".join(f'theme[{name}]="{value}"' for name, value in entries.items()) + "\n"
path = Path(sys.argv[1])
path.parent.mkdir(parents=True, exist_ok=True)
fd, temporary = tempfile.mkstemp(prefix=".nbshell.", dir=path.parent, text=True)
try:
    with os.fdopen(fd, "w") as handle:
        handle.write(content)
    os.replace(temporary, path)
finally:
    if os.path.exists(temporary):
        os.unlink(temporary)
PY

# btop 1.4+ hot-reloads its config and selected theme on SIGUSR2 (Ctrl+R uses
# the same code path). Restrict signaling to this user's exact-name processes.
if command -v pkill >/dev/null 2>&1; then
  pkill -USR2 -x -u "$(id -u)" btop 2>/dev/null || true
fi

# Fcitx5 Classic UI keeps the parsed theme in memory. Generate its static

# theme from the palette exported by nbshell, then reload only Classic UI so

# an active Rime session and its selected schema are not disturbed.
fcitx_theme="${XDG_DATA_HOME:-$HOME/.local/share}/fcitx5/themes/Nbshell/theme.conf"
mkdir -p "$(dirname "$fcitx_theme")"
python3 - "$fcitx_theme" <<'PY'
from pathlib import Path
import os
import re
import sys
import tempfile

palette = Path.home() / ".config/nbshell/palette.sh"
colors = {}
for line in palette.read_text().splitlines():
    match = re.match(r"NB_([A-Z_]+)='([^']*)'$", line)
    if match:
        colors[match.group(1)] = match.group(2)

def color(name, fallback):
    return colors.get(name, fallback)

theme = colors.get("THEME", "nbshell")
fg = color("FG", "#ffffff")
fg_bright = color("FG_BRIGHT", fg)
bg_dark = color("BG_DARK", color("BG", "#000000"))
muted = color("MUTED", color("FG_DIM", "#808080"))
accent = color("ACCENT", color("BLUE", "#5f87ff"))
selection = color("SELECTION", color("BG_LIGHT", bg_dark))
content = f'''# Generated by nbshell theme-hook — Theme: {theme}
[Metadata]
Name=Nbshell
Version=1
Author=dotfiles
Description="Fcitx5 candidate panel synchronized with nbshell"

[InputPanel]
NormalColor={fg}
HighlightColor={accent}
HighlightBackgroundColor=#00000000
HighlightCandidateColor={fg_bright}
EnableBlur=False
FullWidthHighlight=True
PageButtonAlignment=Bottom

[InputPanel/Background]
Color={bg_dark}
BorderColor={muted}
BorderWidth=1

[InputPanel/Background/Margin]
Left=8
Right=8
Top=6
Bottom=6

[InputPanel/Highlight]
Color={selection}
BorderColor={accent}
BorderWidth=1

[InputPanel/Highlight/Margin]
Left=8
Right=8
Top=5
Bottom=5

[InputPanel/ContentMargin]
Left=3
Right=3
Top=3
Bottom=3

[InputPanel/TextMargin]
Left=8
Right=8
Top=5
Bottom=5

[Menu]
NormalColor={fg}
HighlightCandidateColor={fg_bright}
Spacing=2

[Menu/Background]
Color={bg_dark}
BorderColor={muted}
BorderWidth=1

[Menu/Background/Margin]
Left=5
Right=5
Top=5
Bottom=5

[Menu/Highlight]
Color={selection}
BorderColor={accent}
BorderWidth=1

[Menu/Highlight/Margin]
Left=7
Right=7
Top=4
Bottom=4

[Menu/Separator]
Color={muted}
BorderColor=#00000000
BorderWidth=0

[Menu/ContentMargin]
Left=3
Right=3
Top=3
Bottom=3

[Menu/TextMargin]
Left=6
Right=6
Top=4
Bottom=4
'''
path = Path(sys.argv[1])
fd, temporary = tempfile.mkstemp(prefix=".nbshell.", dir=path.parent, text=True)
try:
    with os.fdopen(fd, "w") as handle:
        handle.write(content)
    os.replace(temporary, path)
finally:
    if os.path.exists(temporary):
        os.unlink(temporary)
PY

if command -v busctl >/dev/null 2>&1 && busctl --user status org.fcitx.Fcitx5 >/dev/null 2>&1; then
  busctl --user call org.fcitx.Fcitx5 /controller org.fcitx.Fcitx.Controller1 ReloadAddonConfig s classicui >/dev/null 2>&1 || \
    fcitx5-remote -r >/dev/null 2>&1 || true
elif command -v fcitx5-remote >/dev/null 2>&1; then
  fcitx5-remote --check >/dev/null 2>&1 && fcitx5-remote -r >/dev/null 2>&1 || true
fi

# ── GTK + XDG portal + Chromium theme: GUI apps ───────────────────────────
# GTK3/GTK4 are recolored through the per-user css override: the default
# themes are built from named colors and ~/.config/gtk-{3,4}.0/gtk.css is
# stacked on top of them. Chromium (since ~M121) no longer paints its own
# chrome from GTK theme colors — it only takes the light/dark preference —
# so its toolbar/omnibus colors come from the theme extension generated
# below; GTK4 apps additionally follow the portal color-scheme.
python3 - "${XDG_CONFIG_HOME:-$HOME/.config}" <<'PY'
from pathlib import Path
import configparser
import json
import os
import re
import sys
import tempfile

config_home = Path(sys.argv[1])
colors = {}
for line in (config_home / "nbshell" / "palette.sh").read_text().splitlines():
    match = re.match(r"NB_([A-Z_]+)='([^']*)'$", line)
    if match:
        colors[match.group(1)] = match.group(2)

def color(name, fallback):
    return colors.get(name, fallback)

theme = color("THEME", "nbshell")
dark = color("MODE", "dark") != "light"
bg = color("BG", "#1a1b26" if dark else "#eff1f5")
bg_dark = color("BG_DARK", bg)
bg_light = color("BG_LIGHT", bg)
fg = color("FG", "#a9b1d6" if dark else "#4c4f69")
fg_dim = color("FG_DIM", color("MUTED", "#808080"))
muted = color("MUTED", fg_dim)
accent = color("ACCENT", color("BLUE", "#5f87ff"))
selection = color("SELECTION", bg_light)
red = color("RED", "#ff0000")
green = color("GREEN", "#00ff00")
yellow = color("YELLOW", "#ffff00")
blue = color("BLUE", accent)
magenta = color("MAGENTA", "#ff00ff")

def atomic_write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, temporary = tempfile.mkstemp(prefix=".nbshell.", dir=path.parent, text=True)
    try:
        with os.fdopen(fd, "w") as handle:
            handle.write(content)
        os.chmod(temporary, 0o644)
        os.replace(temporary, path)
    finally:
        if os.path.exists(temporary):
            os.unlink(temporary)

# Only manage css files that are empty, absent or already generated here;
# a hand-written gtk.css stays untouched.
def write_css(path: Path, content: str) -> None:
    if path.exists() and path.stat().st_size > 0:
        if "Generated by nbshell" not in path.read_text(errors="replace"):
            print(f"nbshell theme-hook: keeping unmanaged {path}", file=sys.stderr)
            return
    atomic_write(path, content)

header = f"""/* Generated by nbshell theme-hook — Theme: {theme} */
/* Do not edit manually; every theme change overwrites this file. */
"""

# GTK3: named colors of the built-in Adwaita theme.
gtk3_css = header + f"""
@define-color theme_bg_color {bg};
@define-color theme_fg_color {fg};
@define-color theme_base_color {bg_dark};
@define-color theme_text_color {fg};
@define-color theme_selected_bg_color {accent};
@define-color theme_selected_fg_color {bg};
@define-color theme_unfocused_bg_color {bg};
@define-color theme_unfocused_fg_color {fg_dim};
@define-color theme_unfocused_base_color {bg_dark};
@define-color theme_unfocused_text_color {fg_dim};
@define-color theme_unfocused_selected_bg_color {muted};
@define-color theme_unfocused_selected_fg_color {fg};
@define-color insensitive_bg_color {bg_dark};
@define-color insensitive_fg_color {fg_dim};
@define-color insensitive_base_color {bg_dark};
@define-color borders {muted};
@define-color unfocused_borders {muted};
@define-color warning_color {yellow};
@define-color error_color {red};
@define-color success_color {green};
@define-color placeholder_text_color {fg_dim};
@define-color link_color {blue};
@define-color link_visited_color {magenta};
@define-color content_view_bg {bg_dark};
@define-color wm_title {fg};
@define-color wm_unfocused_title {fg_dim};
@define-color wm_bg {bg_dark};
@define-color wm_bg_unfocused {bg};
@define-color wm_border {muted};
"""
write_css(config_home / "gtk-3.0" / "gtk.css", gtk3_css)

# GTK4: named colors of the built-in Default theme.
gtk4_css = header + f"""
@define-color accent_color {accent};
@define-color accent_bg_color {accent};
@define-color accent_fg_color {bg};
@define-color destructive_color {red};
@define-color destructive_bg_color {red};
@define-color destructive_fg_color {bg};
@define-color success_color {green};
@define-color success_bg_color {green};
@define-color success_fg_color {bg};
@define-color warning_color {yellow};
@define-color warning_bg_color {yellow};
@define-color warning_fg_color {bg};
@define-color error_color {red};
@define-color error_bg_color {red};
@define-color error_fg_color {bg};
@define-color window_bg_color {bg};
@define-color window_fg_color {fg};
@define-color view_bg_color {bg_dark};
@define-color view_fg_color {fg};
@define-color headerbar_bg_color {bg_dark};
@define-color headerbar_fg_color {fg};
@define-color headerbar_border_color {muted};
@define-color headerbar_backdrop_color {bg};
@define-color headerbar_shade_color {bg_dark};
@define-color card_bg_color {bg_light};
@define-color card_fg_color {fg};
@define-color card_shade_color {bg_dark};
@define-color dialog_bg_color {bg_light};
@define-color dialog_fg_color {fg};
@define-color popover_bg_color {bg_light};
@define-color popover_fg_color {fg};
@define-color popover_shade_color {bg_dark};
@define-color sidebar_bg_color {bg_dark};
@define-color sidebar_fg_color {fg};
@define-color sidebar_backdrop_color {bg};
@define-color secondary_sidebar_bg_color {bg_dark};
@define-color secondary_sidebar_fg_color {fg};
@define-color thumbnail_bg_color {bg_light};
@define-color thumbnail_fg_color {fg};
@define-color shade_color {bg_dark};
@define-color scrollbar_outline_color {muted};
"""
write_css(config_home / "gtk-4.0" / "gtk.css", gtk4_css)

# GTK reads the dark preference from settings.ini (no XSETTINGS exists on
# Wayland); the portal color-scheme below covers GTK4 and Chromium.
for gtk_version in ("gtk-3.0", "gtk-4.0"):
    settings = config_home / gtk_version / "settings.ini"
    parser = configparser.ConfigParser()
    parser.optionxform = str
    parser.read(settings)
    if not parser.has_section("Settings"):
        parser.add_section("Settings")
    parser.set("Settings", "gtk-application-prefer-dark-theme", "1" if dark else "0")
    fd, temporary = tempfile.mkstemp(prefix=".nbshell.", dir=settings.parent, text=True)
    try:
        with os.fdopen(fd, "w") as handle:
            parser.write(handle)
        os.chmod(temporary, 0o644)
        os.replace(temporary, settings)
    finally:
        if os.path.exists(temporary):
            os.unlink(temporary)

# Chromium theme extension: Chromium 121+ computes its own UI colors and
# only follows light/dark from GTK/portal, so the css above leaves its
# toolbar grey. A theme extension recolors frame/toolbar/omnibox/NTP from
# the palette; chromium-flags.conf loads it via --load-extension and it is
# applied when the browser starts.
def rgb_triplet(value):
    digits = value.lstrip("#")
    if len(digits) == 3:
        digits = "".join(ch * 2 for ch in digits)
    return [int(digits[i:i + 2], 16) for i in (0, 2, 4)]

chromium_theme = {
    "manifest_version": 3,
    "version": "1.0",
    "name": f"nbshell {theme}",
    "theme": {
        "colors": {
            "frame": rgb_triplet(bg_dark),
            "frame_inactive": rgb_triplet(bg_dark),
            "toolbar": rgb_triplet(bg),
            "tab_text": rgb_triplet(fg),
            "tab_background_text": rgb_triplet(fg_dim),
            "bookmark_text": rgb_triplet(fg),
            "omnibox_background": rgb_triplet(bg_light),
            "omnibox_text": rgb_triplet(fg),
            "ntp_background": rgb_triplet(bg),
            "ntp_text": rgb_triplet(fg),
            "ntp_link": rgb_triplet(accent),
        },
        "properties": {"ntp_logo_alternate": 1 if dark else 0},
    },
}
atomic_write(
    config_home / "nbshell" / "chromium-theme" / "manifest.json",
    json.dumps(chromium_theme, indent=2) + "\n",
)
PY


# Chromium's managed BrowserThemeColor policy is the reliable live path on
# this system: policy blocks the unpacked theme extension, but the policy file
# is user-writable and Chromium can refresh it without restarting.
chromium_policy=/etc/chromium/policies/managed/color.json
if [ -e "$chromium_policy" ] && [ -w "$chromium_policy" ]; then
  browser_color="${NB_BG:-#1c2027}"
  [ "${NB_MODE:-dark}" = light ] && browser_color="${NB_BG_LIGHT:-$browser_color}"
  python3 - "$chromium_policy" "$browser_color" "${NB_MODE:-dark}" <<'PY'
import json
import os
import sys
import tempfile

path, color, mode = sys.argv[1:]
directory = os.path.dirname(path)
fd, temporary = tempfile.mkstemp(prefix=".nbshell.", dir=directory, text=True)
try:
    with os.fdopen(fd, "w") as handle:
        json.dump({
            "BrowserThemeColor": color,
            "BrowserColorScheme": "light" if mode == "light" else "dark",
        }, handle)
        handle.write("\n")
    os.chmod(temporary, 0o644)
    os.replace(temporary, path)
finally:
    if os.path.exists(temporary):
        os.unlink(temporary)
PY
fi
# Publish the light/dark preference through gsettings. The running
# xdg-desktop-portal (gnome backend) forwards color-scheme to Chromium,
# Electron and GTK4; switching gtk-theme makes running GTK apps reload their
# css — including the overrides generated above. Prefer the system glib2
# gsettings: a Homebrew one cannot see the system dconf database.
gsettings_bin=""
if [ -x /usr/bin/gsettings ]; then
  gsettings_bin=/usr/bin/gsettings
elif command -v gsettings >/dev/null 2>&1; then
  gsettings_bin="$(command -v gsettings)"
fi
if [ -n "$gsettings_bin" ] && "$gsettings_bin" list-schemas 2>/dev/null | grep -qx org.gnome.desktop.interface; then
  interface=org.gnome.desktop.interface
  scheme=prefer-dark
  base_theme=Adwaita-dark
  if [ "${NB_MODE:-dark}" = light ]; then
    scheme=prefer-light
    base_theme=Adwaita
  fi
  "$gsettings_bin" set "$interface" color-scheme "$scheme" 2>/dev/null || true
  current="$($gsettings_bin get "$interface" gtk-theme 2>/dev/null | tr -d \')" || current=""
  # Re-setting the same value emits no change notification; hop through the
  # sibling theme so GTK notices and reloads the regenerated palette.
  if [ "$current" = "$base_theme" ]; then
    hop=Adwaita
    [ "$base_theme" = Adwaita ] && hop=Adwaita-dark
    "$gsettings_bin" set "$interface" gtk-theme "$hop" 2>/dev/null || true
  fi
  "$gsettings_bin" set "$interface" gtk-theme "$base_theme" 2>/dev/null || true
fi

# Make Chromium load the theme extension above at startup. Omarchy's
# /usr/bin/chromium launcher appends every line of chromium-flags.conf to
# the command line; upstream's shell wrapper reads the same file. Plain
# binaries without that launcher are skipped.
chromium_bin="$(command -v chromium 2>/dev/null || true)"
if [ -n "$chromium_bin" ] && grep -aqs chromium-flags.conf "$chromium_bin"; then
  flags_conf="${XDG_CONFIG_HOME:-$HOME/.config}/chromium-flags.conf"
  theme_flag="--load-extension=$HOME/.config/nbshell/chromium-theme"
  if ! grep -qsxF -e "$theme_flag" "$flags_conf"; then
    mkdir -p "$(dirname "$flags_conf")"
    printf '%s\n' "$theme_flag" >> "$flags_conf"
    echo "nbshell theme-hook: added '$theme_flag' to $flags_conf — restart Chromium to apply"
  fi
fi

# Reload Chromium's managed policy after updating BrowserThemeColor. This
# immediately recolors running browser chrome when policy refresh is supported.
if [ -n "$chromium_bin" ] && [ -w /etc/chromium/policies/managed/color.json ]; then
  "$chromium_bin" --refresh-platform-policy --no-startup-window >/dev/null 2>&1 || true
fi

# Route the chromium desktop entries through the controller so the RUNNING
# browser can be recolored live (it needs --remote-debugging-pipe from exec
# time; see chromium-controller.mjs). Regenerated from the packaged file so
# package updates propagate; a hand-customized override stays untouched.
nb_controller="${XDG_CONFIG_HOME:-$HOME/.config}/nbshell/chromium-controller.mjs"
nb_node="$(command -v node 2>/dev/null || true)"
nb_desktop_src=/usr/share/applications/chromium.desktop
nb_desktop_dst="${XDG_DATA_HOME:-$HOME/.local/share}/applications/chromium.desktop"
if [ -f "$nb_controller" ] && [ -n "$nb_node" ] && [ -f "$nb_desktop_src" ]; then
  if [ ! -f "$nb_desktop_dst" ] || grep -qs chromium-controller.mjs "$nb_desktop_dst"; then
    sed "s|Exec=/usr/bin/chromium|Exec=$nb_node $nb_controller|" "$nb_desktop_src" > "$nb_desktop_dst"
  fi
elif [ -f "$nb_desktop_dst" ] && grep -qs chromium-controller.mjs "$nb_desktop_dst"; then
  # controller or node is gone — remove our override so launches keep working
  rm -f "$nb_desktop_dst"
fi

# Live theme reload for a running controller-backed Chromium. Plainly
# launched instances simply pick the regenerated theme up on next start.
nb_sock="${XDG_RUNTIME_DIR:-/run/user/$(id -u)}/nbshell-chromium.sock"
if [ -S "$nb_sock" ]; then
  python3 - "$nb_sock" <<'PYSOCK'
import socket
import sys

try:
    s = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
    s.settimeout(6)
    s.connect(sys.argv[1])
    s.sendall(b"reload")
    reply = s.recv(4096).decode(errors="replace") or "(no reply)"
    print(f"nbshell theme-hook: chromium live theme reload: {reply}")
except OSError as e:
    print(f"nbshell theme-hook: chromium controller unreachable: {e}", file=sys.stderr)
PYSOCK
fi

# Existing Neovim instances watch palette.sh. Newly launched instances load the
# same generated colorscheme from ~/.config/nvim/colors/nbshell.lua.
exit 0
