#!/usr/bin/env bash
# Runs after nbshell exports ~/.config/nbshell/palette.sh.
# Synchronizes applications whose palettes are not managed directly by QML.
set -u

palette="${XDG_CONFIG_HOME:-$HOME/.config}/nbshell/palette.sh"
[ -r "$palette" ] || exit 0
# shellcheck disable=SC1090
. "$palette"

# Herdr supports a fixed set of named base themes. Pick the nearest built-in
# family, then override its UI tokens with the exact nbshell palette.
case "${NB_THEME:-}" in
  catppuccin-latte) herdr_base="catppuccin-latte" ;;
  catppuccin*) herdr_base="catppuccin" ;;
  tokyo-night) herdr_base="tokyo-night" ;;
  gruvbox) herdr_base="gruvbox" ;;
  kanagawa) herdr_base="kanagawa" ;;
  rose-pine) herdr_base="rose-pine" ;;
  nord) herdr_base="nord" ;;
  *solarized*|osaka-jade) herdr_base="solarized" ;;
  *) [ "${NB_MODE:-dark}" = light ] && herdr_base="catppuccin-latte" || herdr_base="terminal" ;;
esac

herdr_config="${XDG_CONFIG_HOME:-$HOME/.config}/herdr/config.toml"
if [ -f "$herdr_config" ]; then
  python3 - "$herdr_config" "$herdr_base" <<'PY'
from pathlib import Path
import re
import sys

path = Path(sys.argv[1])
base = sys.argv[2]
text = path.read_text()
colors = {}
for line in Path.home().joinpath('.config/nbshell/palette.sh').read_text().splitlines():
    m = re.match(r"NB_([A-Z_]+)='([^']*)'$", line)
    if m:
        colors[m.group(1)] = m.group(2)

block = f'''# BEGIN nbshell managed theme
[theme]
name = "{base}"
auto_switch = false

[theme.custom]
sidebar_bg = "{colors.get('BG_DARK', colors['BG'])}"
active_row_bg = "{colors.get('BG_LIGHT', colors['BG'])}"
selection_bg = "{colors.get('SELECTION', colors.get('BG_LIGHT', colors['BG']))}"
panel_bg = "{colors['BG']}"
accent = "{colors['ACCENT']}"
red = "{colors['RED']}"
green = "{colors['GREEN']}"
# END nbshell managed theme'''

managed = re.compile(r'# BEGIN nbshell managed theme.*?# END nbshell managed theme', re.S)
if managed.search(text):
    text = managed.sub(block, text)
else:
    # Replace the existing top-level [theme] section, including theme.custom if
    # present, while preserving all unrelated Herdr configuration.
    section = re.compile(r'(?ms)^\[theme\]\n.*?(?=^\[(?!theme(?:\.|\]))|\Z)')
    if section.search(text):
        text = section.sub(block + '\n\n', text, count=1)
    else:
        text = block + '\n\n' + text
path.write_text(text)
PY
  command -v herdr >/dev/null 2>&1 && herdr server reload-config >/dev/null 2>&1 || true
fi

# Fcitx5 Classic UI keeps the parsed theme in memory. Generate its static

# theme from the palette exported by nbshell, then reload only Classic UI so

# an active Rime session and its selected schema are not disturbed.
fcitx_theme="${XDG_DATA_HOME:-$HOME/.local/share}/fcitx5/themes/Nbshell/theme.conf"
mkdir -p "$(dirname "$fcitx_theme")"
python3 - "$fcitx_theme" <<'PY'
from pathlib import Path
import os
import re
import sys
import tempfile

palette = Path.home() / ".config/nbshell/palette.sh"
colors = {}
for line in palette.read_text().splitlines():
    match = re.match(r"NB_([A-Z_]+)='([^']*)'$", line)
    if match:
        colors[match.group(1)] = match.group(2)

def color(name, fallback):
    return colors.get(name, fallback)

theme = colors.get("THEME", "nbshell")
fg = color("FG", "#ffffff")
fg_bright = color("FG_BRIGHT", fg)
bg_dark = color("BG_DARK", color("BG", "#000000"))
muted = color("MUTED", color("FG_DIM", "#808080"))
accent = color("ACCENT", color("BLUE", "#5f87ff"))
selection = color("SELECTION", color("BG_LIGHT", bg_dark))
content = f'''# Generated by nbshell theme-hook — Theme: {theme}
[Metadata]
Name=Nbshell
Version=1
Author=dotfiles
Description="Fcitx5 candidate panel synchronized with nbshell"

[InputPanel]
NormalColor={fg}
HighlightColor={accent}
HighlightBackgroundColor=#00000000
HighlightCandidateColor={fg_bright}
EnableBlur=False
FullWidthHighlight=True
PageButtonAlignment=Bottom

[InputPanel/Background]
Color={bg_dark}
BorderColor={muted}
BorderWidth=1

[InputPanel/Background/Margin]
Left=8
Right=8
Top=6
Bottom=6

[InputPanel/Highlight]
Color={selection}
BorderColor={accent}
BorderWidth=1

[InputPanel/Highlight/Margin]
Left=8
Right=8
Top=5
Bottom=5

[InputPanel/ContentMargin]
Left=3
Right=3
Top=3
Bottom=3

[InputPanel/TextMargin]
Left=8
Right=8
Top=5
Bottom=5

[Menu]
NormalColor={fg}
HighlightCandidateColor={fg_bright}
Spacing=2

[Menu/Background]
Color={bg_dark}
BorderColor={muted}
BorderWidth=1

[Menu/Background/Margin]
Left=5
Right=5
Top=5
Bottom=5

[Menu/Highlight]
Color={selection}
BorderColor={accent}
BorderWidth=1

[Menu/Highlight/Margin]
Left=7
Right=7
Top=4
Bottom=4

[Menu/Separator]
Color={muted}
BorderColor=#00000000
BorderWidth=0

[Menu/ContentMargin]
Left=3
Right=3
Top=3
Bottom=3

[Menu/TextMargin]
Left=6
Right=6
Top=4
Bottom=4
'''
path = Path(sys.argv[1])
fd, temporary = tempfile.mkstemp(prefix=".nbshell.", dir=path.parent, text=True)
try:
    with os.fdopen(fd, "w") as handle:
        handle.write(content)
    os.replace(temporary, path)
finally:
    if os.path.exists(temporary):
        os.unlink(temporary)
PY

if command -v busctl >/dev/null 2>&1 && busctl --user status org.fcitx.Fcitx5 >/dev/null 2>&1; then
  busctl --user call org.fcitx.Fcitx5 /controller org.fcitx.Fcitx.Controller1 ReloadAddonConfig s classicui >/dev/null 2>&1 || \
    fcitx5-remote -r >/dev/null 2>&1 || true
elif command -v fcitx5-remote >/dev/null 2>&1; then
  fcitx5-remote --check >/dev/null 2>&1 && fcitx5-remote -r >/dev/null 2>&1 || true
fi

# Existing Neovim instances watch palette.sh. Newly launched instances load the
# same generated colorscheme from ~/.config/nvim/colors/nbshell.lua.
exit 0
